"""Iter 344 — Unified Performance / Load test harness.

Modes:
  smoke   — 20 users × 3 rounds. Quick verification.
  load    — 100 users × 30 rounds (~5 min). Production load.
  stress  — ramp 100 → 500 in 50-user steps until error rate > 10 % or p95 > 5 s.
  soak    — 100 users continuous loops for N minutes (default 30).

Per-mode metrics:
  * Latency (avg, p50, p95, p99, max) per endpoint
  * Error rate, timeout rate, HTTP status distribution
  * Throughput (RPS), elapsed seconds
  * Backend CPU + RSS sampled every 5 s from /proc/[pid]/status
  * Memory growth (Δ RSS over the run) — flag soak leaks.
  * Auth token refresh per worker every 60 s.
  * Write endpoints exercised (POST bookings stub, POST tasks).

Reports written to /app/test_reports/perf_iter344/.

Usage:
    python3 /app/backend/tests/load/loadtest.py --mode smoke
    python3 /app/backend/tests/load/loadtest.py --mode load
    python3 /app/backend/tests/load/loadtest.py --mode stress
    python3 /app/backend/tests/load/loadtest.py --mode soak --soak-min 30
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import statistics
import sys
import time
from pathlib import Path

import aiohttp

BASE = os.environ.get("LOAD_BASE_URL") or "http://localhost:8001"
USERNAME = os.environ.get("LOAD_USER", "admin@meetflow.com")
PASSWORD = os.environ.get("LOAD_PASS", "admin123")
REPORT_DIR = Path("/app/test_reports/perf_iter344")
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# Per-endpoint basket: (name, method, path, body_factory_or_None)
READ_ENDPOINTS: list[tuple[str, str, str, object]] = [
    ("auth_me", "GET", "/api/auth/me", None),
    ("dashboard_stats", "GET", "/api/dashboard/stats", None),
    ("tasks_list", "GET", "/api/tasks?limit=50", None),
    ("news_feed", "GET", "/api/news/feed", None),
    ("notifications", "GET", "/api/notifications?limit=20", None),
    ("resources_list", "GET", "/api/resources", None),
    ("my_bookings", "GET", "/api/booking/my-bookings", None),
    ("bookings_list", "GET", "/api/resource-bookings", None),
    ("calendar_events", "GET", "/api/calendar/events", None),
    ("chat_conversations", "GET", "/api/chat/conversations", None),
    ("chat_unread", "GET", "/api/chat/unread-summary", None),
    ("users_directory", "GET", "/api/chat/users", None),
    ("user_permissions", "GET", "/api/user/permissions", None),
    ("catering_items", "GET", "/api/catering-items", None),
    ("cost_centers", "GET", "/api/cost-centers", None),
]

# Write endpoints are rate-limited inside the test to a small fraction of
# total requests so we don't pollute the DB with millions of test rows.
def _booking_body():
    """Returns a far-future booking the user can immediately delete."""
    import uuid
    return {
        # resource_id is filled in at runtime from the first resource fetched.
        "title": f"loadtest-{uuid.uuid4().hex[:6]}",
        "start_at": "2030-01-01T10:00:00Z",
        "end_at": "2030-01-01T11:00:00Z",
    }


def _task_body():
    import uuid
    return {
        "title": f"loadtest-{uuid.uuid4().hex[:6]}",
        "description": "Auto-generated by Iter 344 load test",
        "status": "open",
        "priority": "low",
    }


# ----------------- Auth helpers -----------------

async def login(session: aiohttp.ClientSession) -> str:
    async with session.post(
        f"{BASE}/api/auth/login",
        json={"email": USERNAME, "password": PASSWORD},
        timeout=aiohttp.ClientTimeout(total=30),
    ) as r:
        if r.status != 200:
            txt = await r.text()
            raise RuntimeError(f"login failed {r.status}: {txt[:200]}")
        data = await r.json()
        return data.get("token") or data.get("access_token") or ""


# ----------------- Hit helper -----------------

async def hit(session: aiohttp.ClientSession, method: str, url: str, headers: dict,
              body=None, timeout=30) -> tuple[int, float, int]:
    """Returns (status_code, elapsed_seconds, body_size_bytes)."""
    t0 = time.perf_counter()
    try:
        async with session.request(
            method, url, headers=headers, json=body if body is not None else None,
            timeout=aiohttp.ClientTimeout(total=timeout),
        ) as r:
            payload = await r.read()
            return r.status, time.perf_counter() - t0, len(payload)
    except asyncio.TimeoutError:
        return 0, time.perf_counter() - t0, 0
    except Exception:
        return -1, time.perf_counter() - t0, 0


# ----------------- Worker -----------------

async def user_worker(uid: int, token_holder: dict, rounds: int, results: dict,
                      connector: aiohttp.TCPConnector, stop_event: asyncio.Event,
                      write_share: float = 0.02):
    """One virtual user. Each round hits the full read basket once; with
    `write_share` probability we also fire a booking POST + delete + task POST + delete.
    """
    import random
    async with aiohttp.ClientSession(connector=connector, connector_owner=False) as session:
        for r_idx in range(rounds):
            if stop_event.is_set():
                return
            headers = {"Authorization": f"Bearer {token_holder['token']}"}
            for name, method, path, _factory in READ_ENDPOINTS:
                if stop_event.is_set():
                    return
                status, dt, sz = await hit(session, method, f"{BASE}{path}", headers)
                _record(results, name, status, dt, sz)
            # Write share — exercise mutation paths under the same token.
            if random.random() < write_share:
                # Tasks POST + DELETE — purely additive, easy to clean up.
                status, dt, sz = await hit(
                    session, "POST", f"{BASE}/api/tasks", headers, body=_task_body(),
                )
                _record(results, "tasks_create", status, dt, sz)
                if status == 200:
                    # tiny GET to consume the response and delete
                    try:
                        async with session.get(f"{BASE}/api/tasks?limit=1", headers=headers, timeout=aiohttp.ClientTimeout(total=10)) as r:
                            data = await r.json()
                            if data and isinstance(data, list) and data and data[0].get("task_id"):
                                tid = data[0]["task_id"]
                                await session.delete(f"{BASE}/api/tasks/{tid}", headers=headers,
                                                     timeout=aiohttp.ClientTimeout(total=10))
                    except Exception:
                        pass


def _record(results: dict, name: str, status: int, dt: float, sz: int):
    b = results.setdefault(name, {"latencies": [], "ok": 0, "err": 0, "timeout": 0, "bytes": 0, "status_codes": {}})
    b["latencies"].append(dt)
    b["bytes"] += sz
    b["status_codes"][status] = b["status_codes"].get(status, 0) + 1
    if status == 200:
        b["ok"] += 1
    elif status == 0:
        b["timeout"] += 1
    else:
        b["err"] += 1


# ----------------- Backend resource sampler -----------------

async def backend_sampler(stop_event: asyncio.Event, samples: list, interval_s: int = 5):
    """Sample backend uvicorn worker CPU+RSS every `interval_s` seconds."""
    import subprocess
    while not stop_event.is_set():
        try:
            # Sum across all uvicorn workers
            r = subprocess.run(
                ["bash", "-c", "ps -eo rss=,pcpu=,cmd= | grep '[u]vicorn server:app' | awk '{r+=$1; c+=$2} END {print r\" \"c}'"],
                capture_output=True, text=True, timeout=2,
            )
            parts = r.stdout.strip().split()
            if len(parts) == 2:
                rss_kb, cpu = int(parts[0]), float(parts[1])
                samples.append({"t": time.time(), "rss_mb": round(rss_kb / 1024, 1), "cpu_pct": round(cpu, 1)})
        except Exception:
            pass
        try:
            await asyncio.wait_for(stop_event.wait(), timeout=interval_s)
        except asyncio.TimeoutError:
            pass


# ----------------- Token refresher -----------------

async def token_refresher(token_holder: dict, stop_event: asyncio.Event, every_s: int = 60):
    """Re-login every `every_s` seconds to exercise the auth path and prove
    token issuance stays responsive during the run. Refresh failures count
    via a separate `_auth_refresh` endpoint bucket.
    """
    while not stop_event.is_set():
        try:
            await asyncio.wait_for(stop_event.wait(), timeout=every_s)
            break
        except asyncio.TimeoutError:
            pass
        try:
            async with aiohttp.ClientSession() as s:
                t0 = time.perf_counter()
                async with s.post(
                    f"{BASE}/api/auth/login",
                    json={"email": USERNAME, "password": PASSWORD},
                    timeout=aiohttp.ClientTimeout(total=15),
                ) as r:
                    data = await r.json() if r.status == 200 else {}
                    elapsed = time.perf_counter() - t0
                    token_holder.setdefault("refresh_log", []).append({
                        "status": r.status, "elapsed_s": round(elapsed, 3),
                    })
                    if r.status == 200:
                        tok = data.get("token") or data.get("access_token")
                        if tok:
                            token_holder["token"] = tok
        except Exception as e:
            token_holder.setdefault("refresh_log", []).append({
                "status": -1, "error": str(e)[:80],
            })


# ----------------- Stats helpers -----------------

def percentile(values, q):
    if not values:
        return 0.0
    s = sorted(values)
    k = int(round((len(s) - 1) * q))
    return s[k]


def summarise(name, b):
    lats = b["latencies"]
    calls = len(lats)
    return {
        "endpoint": name,
        "calls": calls,
        "ok": b["ok"],
        "err": b["err"],
        "timeout": b["timeout"],
        "err_rate_pct": round(100 * (b["err"] + b["timeout"]) / max(1, calls), 2),
        "avg_ms": round(1000 * statistics.fmean(lats), 1) if lats else 0,
        "p50_ms": round(1000 * percentile(lats, 0.5), 1),
        "p95_ms": round(1000 * percentile(lats, 0.95), 1),
        "p99_ms": round(1000 * percentile(lats, 0.99), 1),
        "max_ms": round(1000 * max(lats), 1) if lats else 0,
        "bytes": b["bytes"],
        "status_codes": b["status_codes"],
    }


# ----------------- Mode runners -----------------

async def run_phase(users: int, rounds: int, label: str, write_share: float = 0.0,
                    duration_s: int | None = None) -> dict:
    """Run a single load phase. `duration_s` if provided overrides `rounds`
    (worker keeps looping until time elapses); used for soak mode.
    """
    async with aiohttp.ClientSession() as s:
        tok = await login(s)
    token_holder = {"token": tok, "refresh_log": []}

    results = {}
    samples = []
    stop_event = asyncio.Event()
    connector = aiohttp.TCPConnector(limit=400, limit_per_host=400, ssl=False)

    sampler_task = asyncio.create_task(backend_sampler(stop_event, samples))
    refresher_task = asyncio.create_task(token_refresher(token_holder, stop_event))

    t_start = time.perf_counter()
    if duration_s:
        # Soak: workers loop forever, we cancel them when duration elapses.
        # rounds large enough to never be the limiting factor at this duration.
        worker_rounds = 10_000_000
        async def stopper():
            await asyncio.sleep(duration_s)
            stop_event.set()
        stopper_task = asyncio.create_task(stopper())
    else:
        worker_rounds = rounds
        stopper_task = None

    try:
        await asyncio.gather(
            *(user_worker(i, token_holder, worker_rounds, results, connector, stop_event, write_share)
              for i in range(users)),
            return_exceptions=True,
        )
    finally:
        stop_event.set()
        await connector.close()
        if stopper_task:
            stopper_task.cancel()
        sampler_task.cancel()
        refresher_task.cancel()
        await asyncio.gather(sampler_task, refresher_task, return_exceptions=True)

    elapsed = time.perf_counter() - t_start
    rows = [summarise(n, b) for n, b in results.items()]
    rows.sort(key=lambda r: r["p95_ms"], reverse=True)
    total_calls = sum(r["calls"] for r in rows)
    total_err = sum(r["err"] + r["timeout"] for r in rows)
    all_lats = [v for b in results.values() for v in b["latencies"]]

    rss_max = max((s["rss_mb"] for s in samples), default=0)
    rss_min = min((s["rss_mb"] for s in samples), default=0)
    cpu_max = max((s["cpu_pct"] for s in samples), default=0)

    return {
        "phase": label, "users": users,
        "rounds": rounds if not duration_s else None,
        "duration_target_s": duration_s,
        "elapsed_s": round(elapsed, 2),
        "rps": round(total_calls / elapsed, 2) if elapsed > 0 else 0,
        "total_calls": total_calls, "errors": total_err,
        "error_rate_pct": round(100 * total_err / max(1, total_calls), 2),
        "overall_avg_ms": round(1000 * statistics.fmean(all_lats), 1) if all_lats else 0,
        "overall_p95_ms": round(1000 * percentile(all_lats, 0.95), 1),
        "overall_p99_ms": round(1000 * percentile(all_lats, 0.99), 1),
        "backend_rss_mb_min": rss_min,
        "backend_rss_mb_max": rss_max,
        "backend_rss_delta_mb": round(rss_max - rss_min, 1) if rss_min else 0,
        "backend_cpu_pct_max": cpu_max,
        "samples": samples,
        "token_refreshes": len(token_holder.get("refresh_log", [])),
        "token_refresh_failures": sum(1 for r in token_holder.get("refresh_log", []) if r.get("status") != 200),
        "endpoints": rows,
    }


def print_phase(p: dict):
    print(f"\n## {p['phase'].upper()} ({p['users']} users, {p['elapsed_s']}s, {p['rps']} RPS)")
    print(f"  Total calls: {p['total_calls']}, Errors: {p['errors']} ({p['error_rate_pct']}%)")
    print(f"  Overall  avg={p['overall_avg_ms']}ms  p95={p['overall_p95_ms']}ms  p99={p['overall_p99_ms']}ms")
    print(f"  Backend RSS: {p['backend_rss_mb_min']} → {p['backend_rss_mb_max']} MB (Δ {p['backend_rss_delta_mb']}); CPU max {p['backend_cpu_pct_max']}%")
    print(f"  Token refresh: {p['token_refreshes']} total, {p['token_refresh_failures']} failed")
    print(f"  {'endpoint':<22} {'calls':>6} {'err':>4} {'avg':>7} {'p50':>7} {'p95':>7} {'p99':>7}")
    for r in p["endpoints"][:8]:
        print(f"  {r['endpoint']:<22} {r['calls']:>6} {r['err']+r['timeout']:>4} "
              f"{r['avg_ms']:>7.1f} {r['p50_ms']:>7.1f} {r['p95_ms']:>7.1f} {r['p99_ms']:>7.1f}")


async def smoke():
    return await run_phase(users=20, rounds=3, label="smoke", write_share=0.05)


async def load():
    return await run_phase(users=100, rounds=30, label="load", write_share=0.01)


async def stress():
    """Ramp 100 → 500 in 50-user steps. Stop early if error_rate > 10 %
    or overall p95 > 5000 ms."""
    out = []
    for users in (100, 150, 200, 250, 300, 350, 400, 450, 500):
        p = await run_phase(users=users, rounds=5, label=f"stress_{users}", write_share=0.0)
        out.append(p)
        print_phase(p)
        if p["error_rate_pct"] > 10:
            print(f"\n  >>> Aborting ramp at {users} users: error_rate_pct={p['error_rate_pct']}%")
            break
        if p["overall_p95_ms"] > 5000:
            print(f"\n  >>> Aborting ramp at {users} users: p95={p['overall_p95_ms']}ms")
            break
    return out


async def soak(minutes: int):
    return await run_phase(users=100, rounds=0, label=f"soak_{minutes}min",
                           write_share=0.005, duration_s=minutes * 60)


# ----------------- Markdown report writer -----------------

def write_markdown_report(mode: str, phases: list[dict]):
    out = [f"# Performance-Bericht — Modus: `{mode}`", ""]
    out.append(f"- Basis-URL: `{BASE}`")
    out.append(f"- Generiert: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}")
    out.append("")
    out.append("## Übersicht")
    out.append("| Phase | Users | Dauer (s) | Calls | Errors | Err% | RPS | avg ms | p95 ms | p99 ms | Backend RSS Δ | CPU max | Token-Refresh fail |")
    out.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for p in phases:
        out.append(
            f"| {p['phase']} | {p['users']} | {p['elapsed_s']} | {p['total_calls']} | "
            f"{p['errors']} | {p['error_rate_pct']} | {p['rps']} | "
            f"{p['overall_avg_ms']} | {p['overall_p95_ms']} | {p['overall_p99_ms']} | "
            f"{p['backend_rss_delta_mb']} MB | {p['backend_cpu_pct_max']}% | "
            f"{p['token_refresh_failures']}/{p['token_refreshes']} |"
        )
    out.append("")
    for p in phases:
        out.append(f"## {p['phase']} — Endpoint-Tabelle")
        out.append("| Endpoint | Calls | Err | avg | p50 | p95 | p99 | max | Status-Codes |")
        out.append("|---|---|---|---|---|---|---|---|---|")
        for r in p["endpoints"]:
            sc = ", ".join(f"{k}:{v}" for k, v in sorted(r["status_codes"].items()))
            out.append(
                f"| `{r['endpoint']}` | {r['calls']} | {r['err']+r['timeout']} | "
                f"{r['avg_ms']} | {r['p50_ms']} | {r['p95_ms']} | {r['p99_ms']} | "
                f"{r['max_ms']} | {sc} |"
            )
        out.append("")
    out.append("## Bewertung & Bottleneck-Analyse")
    worst = []
    for p in phases:
        for r in p["endpoints"]:
            if r["p95_ms"] > 1000 or r["err_rate_pct"] > 1:
                worst.append((p["phase"], r))
    if worst:
        out.append("Auffällige Endpoints (p95 > 1 s oder Fehlerrate > 1 %):")
        out.append("")
        for phase, r in sorted(worst, key=lambda x: x[1]["p95_ms"], reverse=True)[:15]:
            out.append(f"- `{r['endpoint']}` in `{phase}`: p95 {r['p95_ms']} ms, err {r['err_rate_pct']} %")
    else:
        out.append("Keine kritischen Endpoints — alle p95 < 1 s und Fehlerrate < 1 %.")
    out.append("")
    out.append("### Empfehlungen")
    out.append("- Falls Stress vor 500 Usern abbricht: weiteren uvicorn-Worker hinzufügen (`--workers 8`) oder Connection-Pool prüfen.")
    out.append("- Soak: wenn `backend_rss_delta_mb` > 200 MB nach 30 min → Heap-Leak-Verdacht, mit tracemalloc nachschauen.")
    out.append("- Token-Refresh-Failures > 0 unter Load → Auth-Pfad nicht uvloop-fit (z.B. blockierender bcrypt-Hash).")
    out.append("- Endpoints mit höchstem p95 sind Kandidaten für TTL-Cache (`fastapi-cache2`) oder DB-Index-Review.")
    path = REPORT_DIR / "REPORT.md"
    path.write_text("\n".join(out))
    print(f"\n>> Report: {path}")
    json_path = REPORT_DIR / f"{mode}.json"
    json_path.write_text(json.dumps(phases, indent=2))
    print(f">> JSON  : {json_path}")


# ----------------- Main -----------------

async def main_async(args):
    if args.mode == "smoke":
        p = await smoke()
        print_phase(p)
        write_markdown_report("smoke", [p])
    elif args.mode == "load":
        p = await load()
        print_phase(p)
        write_markdown_report("load", [p])
    elif args.mode == "stress":
        phases = await stress()
        write_markdown_report("stress", phases)
    elif args.mode == "soak":
        p = await soak(args.soak_min)
        print_phase(p)
        write_markdown_report(f"soak_{args.soak_min}min", [p])
    elif args.mode == "full":
        sm = await smoke()
        print_phase(sm)
        ld = await load()
        print_phase(ld)
        st = await stress()
        write_markdown_report("full", [sm, ld] + st)
    else:
        print(f"Unknown mode: {args.mode}")
        return 2
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["smoke", "load", "stress", "soak", "full"], required=True)
    ap.add_argument("--soak-min", type=int, default=30)
    a = ap.parse_args()
    sys.exit(asyncio.run(main_async(a)))
